# Generated by Django 4.0 on 2021-12-25 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(related_name='token_groups', related_query_name='token_group', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('token', models.SlugField(editable=False, max_length=30, unique=True)),
                ('token_groups', models.ManyToManyField(related_name='token_users', related_query_name='token_user', to='graphics_token.TokenGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
